//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Migrator29EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class AGENCIA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AGENCIA()
        {
            this.ATM = new HashSet<ATM>();
            this.LOG = new HashSet<LOG>();
            this.PUNTOPAGO = new HashSet<PUNTOPAGO>();
            this.TARJETA = new HashSet<TARJETA>();
            this.USUARIO = new HashSet<USUARIO>();
            this.USUARIO_PPAGO = new HashSet<USUARIO_PPAGO>();
        }
    
        public int AGE_CODIGO { get; set; }
        public string INST_CODIGO { get; set; }
        public string AGE_DESCRIPCION { get; set; }
        public string AGE_ESTADO { get; set; }
        public Nullable<int> CIU_CODIGO { get; set; }
        public string AGE_UBICACION { get; set; }
        public string AGE_ZONA { get; set; }
    
        public virtual CIUDAD CIUDAD { get; set; }
        public virtual INSTITUCION INSTITUCION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ATM> ATM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LOG> LOG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PUNTOPAGO> PUNTOPAGO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TARJETA> TARJETA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USUARIO> USUARIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USUARIO_PPAGO> USUARIO_PPAGO { get; set; }
    }
}
