//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Migrator29EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApiKeys
    {
        public string Id { get; set; }
        public long InstId { get; set; }
        public System.DateTime Creation { get; set; }
        public System.DateTime Expiration { get; set; }
        public string Hash { get; set; }
    }
}
