//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Migrator29EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class APLICACION_ESTADO_TARJETA
    {
        public int EST_TAR_CODIGO { get; set; }
        public string HABILITAR_TAR_NUMERO { get; set; }
        public string HABILITAR_TIP_TAR_CODIGO { get; set; }
        public string HABILITAR_EST_TAR_CODIGO { get; set; }
        public string HABILITAR_TAR_FECHA_SOLICITUD { get; set; }
        public string HABILITAR_TAR_CUPO_DIARIO_ATM { get; set; }
        public string HABILITAR_TAR_FECHA_EXPIRACION { get; set; }
        public string HABILITAR_TAR_FECHA_ENTREGA { get; set; }
        public string HABILITAR_TAR_NOMBRE_IMPRESO { get; set; }
        public string HABILITAR_ORD_CODIGO { get; set; }
        public string HABILITAR_AGE_CODIGO { get; set; }
        public string HABILITAR_AGE_DESCRIPTION_E { get; set; }
        public string HABILITAR_TAR_CELULAR { get; set; }
        public string HABILITAR_CTA_NUMERO { get; set; }
        public string HABILITAR_EST_CTA_CODIGO { get; set; }
        public string HABILITAR_TIP_CTA_CODIGO { get; set; }
        public string HABILITAR_CLI_NOMBRE { get; set; }
        public string HABILITAR_CLI_IDENTIFICACION { get; set; }
        public string HABILITAR_CLI_TELEFONO1 { get; set; }
        public string HABILITAR_CLI_TELEFONO2 { get; set; }
        public string HABILITAR_CLI_DIRECCION { get; set; }
        public string HABILITAR_CLI_E_MAIL { get; set; }
    
        public virtual ESTADO_TARJETA ESTADO_TARJETA { get; set; }
    }
}
