//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Migrator29EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ATM
    {
        public string ATM_CODIGO { get; set; }
        public Nullable<int> AGE_CODIGO { get; set; }
        public string ATM_USER { get; set; }
    
        public virtual AGENCIA AGENCIA { get; set; }
    }
}
