//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Migrator29EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditLogs
    {
        public int Id { get; set; }
        public string Entity { get; set; }
        public string Activity { get; set; }
        public System.DateTime Date { get; set; }
        public string User { get; set; }
        public string Institution { get; set; }
        public string Result { get; set; }
        public string Description { get; set; }
    }
}
