//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Migrator29EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Branches
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Branches()
        {
            this.Logs = new HashSet<Logs>();
        }
    
        public int Id { get; set; }
        public long InstitutionId { get; set; }
        public bool State { get; set; }
        public string City { get; set; }
        public string Province { get; set; }
        public string Location { get; set; }
        public string Zone { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string CoreIdentifier { get; set; }
        public string Identifiers { get; set; }
    
        public virtual Institutions Institutions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Logs> Logs { get; set; }
    }
}
