//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Migrator29EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cards
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cards()
        {
            this.CardsAccounts = new HashSet<CardsAccounts>();
        }
    
        public int Id { get; set; }
        public Nullable<int> ProfileId { get; set; }
        public int OrderId { get; set; }
        public Nullable<int> BatchId { get; set; }
        public int State { get; set; }
        public Nullable<System.DateTime> ExpirationDate { get; set; }
        public Nullable<System.DateTime> LastMovDate { get; set; }
        public Nullable<System.DateTime> EmissionDate { get; set; }
        public Nullable<System.DateTime> PINLastChangeDate { get; set; }
        public Nullable<int> ClientId { get; set; }
        public Nullable<decimal> CashQuota { get; set; }
        public Nullable<decimal> PurchaseQuota { get; set; }
        public string OFFSET { get; set; }
        public string Sequential { get; set; }
        public Nullable<int> PINAttempts { get; set; }
        public Nullable<int> ATC_EMV { get; set; }
        public string PrintedName { get; set; }
        public Nullable<int> DeliveryBranchId { get; set; }
        public Nullable<int> ModelId { get; set; }
        public string MaskedNumber { get; set; }
        public string HASH { get; set; }
        public string Seed { get; set; }
        public Nullable<bool> ChangePIN { get; set; }
        public Nullable<System.DateTime> LastCashDate { get; set; }
        public Nullable<System.DateTime> LastPurchaseDate { get; set; }
        public Nullable<System.DateTime> CardDeliveryDate { get; set; }
        public Nullable<System.DateTime> CardActivationDate { get; set; }
        public Nullable<int> CashTransPerDay { get; set; }
        public Nullable<int> RequestBranchId { get; set; }
        public string CardNumber { get; set; }
        public Nullable<System.DateTime> LastMaintenanceFeeChargeDate { get; set; }
        public string LastTransactions { get; set; }
    
        public virtual Orders Orders { get; set; }
        public virtual Profiles Profiles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CardsAccounts> CardsAccounts { get; set; }
    }
}
