//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Migrator29EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CardDBEntities : DbContext
    {
        public CardDBEntities()
            : base("name=CardDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BINs> BINs { get; set; }
        public virtual DbSet<CardBatches> CardBatches { get; set; }
        public virtual DbSet<CardRequests> CardRequests { get; set; }
        public virtual DbSet<Cards> Cards { get; set; }
        public virtual DbSet<CardsAccounts> CardsAccounts { get; set; }
        public virtual DbSet<Clients> Clients { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }
        public virtual DbSet<OrdersTags> OrdersTags { get; set; }
        public virtual DbSet<Prefixes> Prefixes { get; set; }
        public virtual DbSet<Profiles> Profiles { get; set; }
        public virtual DbSet<Providers> Providers { get; set; }
        public virtual DbSet<Tags> Tags { get; set; }
        public virtual DbSet<DenariusTerminals> DenariusTerminals { get; set; }
    }
}
