//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Migrator29EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CardModules
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public long ResourceId { get; set; }
        public string SearchUrl { get; set; }
        public string DBConnectionString { get; set; }
        public string CVVUrl { get; set; }
        public string PANHashTable { get; set; }
        public string DebitUrl { get; set; }
        public Nullable<bool> Bioserver { get; set; }
        public Nullable<bool> Contracts { get; set; }
        public string EntityRef { get; set; }
        public string NotificationUrl { get; set; }
        public string BioServerUrl { get; set; }
        public Nullable<bool> Associates { get; set; }
        public Nullable<bool> MoreThanOneCard { get; set; }
        public string DBBackUpConnectionString { get; set; }
        public string CVVConfig { get; set; }
        public string DebitSchedule { get; set; }
        public Nullable<int> DebitVersion { get; set; }
        public Nullable<bool> Nominadas { get; set; }
        public Nullable<bool> Innominadas { get; set; }
        public string Config { get; set; }
    }
}
