//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Migrator29EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CardMasterEntities : DbContext
    {
        public CardMasterEntities()
            : base("name=CardMasterEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AGENCIA> AGENCIA { get; set; }
        public virtual DbSet<APLICACION_ESTADO_TARJETA> APLICACION_ESTADO_TARJETA { get; set; }
        public virtual DbSet<ATM> ATM { get; set; }
        public virtual DbSet<CIUDAD> CIUDAD { get; set; }
        public virtual DbSet<CLIENTE> CLIENTE { get; set; }
        public virtual DbSet<CLIENTE_CUENTA> CLIENTE_CUENTA { get; set; }
        public virtual DbSet<CUENTA> CUENTA { get; set; }
        public virtual DbSet<DATAFAST_ISO_CONFIGURE> DATAFAST_ISO_CONFIGURE { get; set; }
        public virtual DbSet<DATAFAST_ISO_LOG> DATAFAST_ISO_LOG { get; set; }
        public virtual DbSet<DATAFAST_RESPONSE_CODES> DATAFAST_RESPONSE_CODES { get; set; }
        public virtual DbSet<ESTADO_CUENTA> ESTADO_CUENTA { get; set; }
        public virtual DbSet<ESTADO_TARJETA> ESTADO_TARJETA { get; set; }
        public virtual DbSet<ESTADOS_TARJETA> ESTADOS_TARJETA { get; set; }
        public virtual DbSet<INPUT_FILE> INPUT_FILE { get; set; }
        public virtual DbSet<INSTITUCION> INSTITUCION { get; set; }
        public virtual DbSet<LOG> LOG { get; set; }
        public virtual DbSet<LOG_ACTUALIZACIONES> LOG_ACTUALIZACIONES { get; set; }
        public virtual DbSet<LOGAUDIT> LOGAUDIT { get; set; }
        public virtual DbSet<MENU> MENU { get; set; }
        public virtual DbSet<MENU_PERFIL> MENU_PERFIL { get; set; }
        public virtual DbSet<MODELO_TARJETA> MODELO_TARJETA { get; set; }
        public virtual DbSet<ORDEN> ORDEN { get; set; }
        public virtual DbSet<PERFIL> PERFIL { get; set; }
        public virtual DbSet<PROVINCIA> PROVINCIA { get; set; }
        public virtual DbSet<PUNTOPAGO> PUNTOPAGO { get; set; }
        public virtual DbSet<TARJETA> TARJETA { get; set; }
        public virtual DbSet<TARJETA_CUENTA> TARJETA_CUENTA { get; set; }
        public virtual DbSet<TARJETA_PROFILE> TARJETA_PROFILE { get; set; }
        public virtual DbSet<TIPO_CUENTA> TIPO_CUENTA { get; set; }
        public virtual DbSet<TIPO_TARJETA> TIPO_TARJETA { get; set; }
        public virtual DbSet<TIPOCANAL> TIPOCANAL { get; set; }
        public virtual DbSet<TIPOENTIDAD> TIPOENTIDAD { get; set; }
        public virtual DbSet<TRANSACCION> TRANSACCION { get; set; }
        public virtual DbSet<USUARIO> USUARIO { get; set; }
        public virtual DbSet<USUARIO_PPAGO> USUARIO_PPAGO { get; set; }
        public virtual DbSet<SOLICITUD_TARJETA> SOLICITUD_TARJETA { get; set; }
    }
}
