//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Migrator29EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CardRequests
    {
        public int Id { get; set; }
        public string CardHolder { get; set; }
        public string Identification { get; set; }
        public string PrintedName { get; set; }
        public decimal Quota { get; set; }
        public string CardProfile { get; set; }
        public string DeliveryAgency { get; set; }
    }
}
