//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Migrator29EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CardsAccounts
    {
        public int Id { get; set; }
        public int CardId { get; set; }
        public string AccountNumber { get; set; }
        public string AccountType { get; set; }
        public bool IsPrincipal { get; set; }
    
        public virtual Cards Cards { get; set; }
    }
}
