//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Migrator29EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CardBatches
    {
        public int Id { get; set; }
        public int OrderId { get; set; }
        public int InitialSequential { get; set; }
        public int Size { get; set; }
        public bool Processed { get; set; }
    }
}
