//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Migrator29EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENTE_CUENTA
    {
        public int CLI_CODIGO { get; set; }
        public string CTA_NUMERO { get; set; }
        public string CLI_CTA_OBSERVACION { get; set; }
        public string INST_CODIGO { get; set; }
        public int TIP_CTA_CODIGO { get; set; }
    
        public virtual CLIENTE CLIENTE { get; set; }
        public virtual CUENTA CUENTA { get; set; }
        public virtual INSTITUCION INSTITUCION { get; set; }
        public virtual TIPO_CUENTA TIPO_CUENTA { get; set; }
    }
}
