//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Migrator29EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENTE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CLIENTE()
        {
            this.CLIENTE_CUENTA = new HashSet<CLIENTE_CUENTA>();
            this.LOG_ACTUALIZACIONES = new HashSet<LOG_ACTUALIZACIONES>();
        }
    
        public int CLI_CODIGO { get; set; }
        public string CLI_IDENTIFICACION { get; set; }
        public string CLI_NOMBRE { get; set; }
        public string CLI_DIRECCCION { get; set; }
        public string CLI_TELEFONO1 { get; set; }
        public string CLI_TELEFONO2 { get; set; }
        public string CLI_E_MAIL { get; set; }
        public Nullable<System.DateTime> CLI_FECHA_CREACION { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CLIENTE_CUENTA> CLIENTE_CUENTA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LOG_ACTUALIZACIONES> LOG_ACTUALIZACIONES { get; set; }
    }
}
