//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Migrator29EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DATAFAST_ISO_LOG
    {
        public string Iso_MessageId { get; set; }
        public string Iso_BitMap_A { get; set; }
        public string Iso_BitMap_B { get; set; }
        public string Iso_PrimaryAccountNumber { get; set; }
        public string Iso_ProcessingCode { get; set; }
        public Nullable<decimal> Iso_TransactionAmount { get; set; }
        public Nullable<decimal> Iso_TransmitionDateTime { get; set; }
        public string Iso_SystemTraceAuditNumber { get; set; }
        public decimal Iso_LocalTranTime { get; set; }
        public decimal Iso_LocalTranDate { get; set; }
        public Nullable<decimal> Iso_ExpirationDate { get; set; }
        public Nullable<decimal> Iso_SettlemenDate { get; set; }
        public Nullable<decimal> Iso_LocalTranDateTime { get; set; }
        public string Iso_MerchantType { get; set; }
        public string Iso_POSEntryMode { get; set; }
        public string Iso_CardSequenceNumber { get; set; }
        public string Iso_AdquiringInstId { get; set; }
        public string Iso_ForwardingInstId { get; set; }
        public string Iso_Track2 { get; set; }
        public string Iso_RetrievalReferenceNumber { get; set; }
        public string Iso_AuthIdResponse { get; set; }
        public string Iso_ResponseCode { get; set; }
        public string Iso_CardAcceptorTrmlId { get; set; }
        public string Iso_CardAcceptorId { get; set; }
        public string Iso_CardAcceptorNameLocation { get; set; }
        public string Iso_TrackI { get; set; }
        public string Iso_AdditionalDataPrivate { get; set; }
        public Nullable<int> Iso_CurrencyCode { get; set; }
        public string Iso_PINData { get; set; }
        public string Iso_SecurityRelatedData { get; set; }
        public string Iso_AdditionalAmounts { get; set; }
        public string Iso_IntegratedCircuitCard { get; set; }
        public string Iso_ReservedporNationalUse_57 { get; set; }
        public string Iso_ReservedporNationalUse_58 { get; set; }
        public string Iso_PointofServiceData { get; set; }
        public string Iso_NetworkData { get; set; }
        public string Iso_OriginalDataElements { get; set; }
        public Nullable<int> Iso_LogStatus { get; set; }
        public Nullable<decimal> Iso_LocalDate { get; set; }
        public Nullable<decimal> Iso_ResponseLocalDate { get; set; }
        public string Iso_ResponseDetails { get; set; }
    }
}
