//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Migrator29EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DATAFAST_ISO_CONFIGURE
    {
        public int bitmapNro { get; set; }
        public Nullable<int> vli { get; set; }
        public Nullable<int> longitud { get; set; }
        public string tipo { get; set; }
    }
}
