//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Migrator29EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DenariusTerminals
    {
        public string TerminalId { get; set; }
        public Nullable<int> Channel { get; set; }
        public string userName { get; set; }
        public int priority { get; set; }
    }
}
