//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Migrator29EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class EntityActivities
    {
        public int Id { get; set; }
        public string EntityName { get; set; }
        public bool EntityVisible { get; set; }
        public string EntityDescription { get; set; }
        public string EntityModule { get; set; }
        public string ActivityName { get; set; }
        public bool ActivityVisible { get; set; }
        public string ActivityDescription { get; set; }
        public bool IsAuditable { get; set; }
    }
}
