//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Migrator29EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESTADO_TARJETA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ESTADO_TARJETA()
        {
            this.ESTADOS_TARJETA = new HashSet<ESTADOS_TARJETA>();
            this.ESTADOS_TARJETA1 = new HashSet<ESTADOS_TARJETA>();
            this.TARJETA = new HashSet<TARJETA>();
        }
    
        public int EST_TAR_CODIGO { get; set; }
        public string EST_TAR_DESCRIPCION { get; set; }
        public string EST_TAR_TIPO { get; set; }
        public string EST_TAR_ISO { get; set; }
        public string EST_TAR_ISO_V1 { get; set; }
    
        public virtual APLICACION_ESTADO_TARJETA APLICACION_ESTADO_TARJETA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ESTADOS_TARJETA> ESTADOS_TARJETA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ESTADOS_TARJETA> ESTADOS_TARJETA1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TARJETA> TARJETA { get; set; }
    }
}
