//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Migrator29EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupPermission
    {
        public long GroupPermissionId { get; set; }
        public long InstitutionId { get; set; }
        public long GroupId { get; set; }
        public long ResourceId { get; set; }
        public string Roles { get; set; }
    }
}
