//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Migrator29EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class INPUT_FILE
    {
        public decimal ID_ARCHIVO { get; set; }
        public string NOMBRE_ARCHIVO { get; set; }
        public string FECHA_ARCHIVO { get; set; }
        public Nullable<System.DateTime> FECHA_ENCRIPCION { get; set; }
        public string ENVIO_SFTP_ARCHIVO { get; set; }
        public string ESTADO_ARCHIVO { get; set; }
    }
}
