//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Migrator29EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class INSTITUCION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public INSTITUCION()
        {
            this.AGENCIA = new HashSet<AGENCIA>();
            this.CLIENTE_CUENTA = new HashSet<CLIENTE_CUENTA>();
            this.CUENTA = new HashSet<CUENTA>();
            this.ORDEN = new HashSet<ORDEN>();
            this.PUNTOPAGO = new HashSet<PUNTOPAGO>();
            this.TARJETA_CUENTA = new HashSet<TARJETA_CUENTA>();
            this.USUARIO = new HashSet<USUARIO>();
            this.USUARIO_PPAGO = new HashSet<USUARIO_PPAGO>();
        }
    
        public string INST_CODIGO { get; set; }
        public string INST_NOMBRE { get; set; }
        public string INST_ABA { get; set; }
        public string INST_PAIS { get; set; }
        public string INST_IP { get; set; }
        public string INST_PUERTO { get; set; }
        public Nullable<int> INST_CUPO_MAXIMO_ATM { get; set; }
        public Nullable<int> INST_CUPO_MAXIMO_POS { get; set; }
        public Nullable<int> INST_ANIO_VALIDEZ_TRJ { get; set; }
        public Nullable<long> INST_ULTIMA_TARJETA { get; set; }
        public Nullable<int> TEN_CODIGO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AGENCIA> AGENCIA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CLIENTE_CUENTA> CLIENTE_CUENTA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CUENTA> CUENTA { get; set; }
        public virtual TIPOENTIDAD TIPOENTIDAD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDEN> ORDEN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PUNTOPAGO> PUNTOPAGO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TARJETA_CUENTA> TARJETA_CUENTA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USUARIO> USUARIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USUARIO_PPAGO> USUARIO_PPAGO { get; set; }
    }
}
