//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Migrator29EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Institutions
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Institutions()
        {
            this.AspNetUsers = new HashSet<AspNetUsers>();
            this.Branches = new HashSet<Branches>();
            this.Logs = new HashSet<Logs>();
        }
    
        public long Id { get; set; }
        public string Name { get; set; }
        public string Domain { get; set; }
        public long IdResource { get; set; }
        public long IAMResourceId { get; set; }
        public Nullable<long> CMResourceId { get; set; }
        public Nullable<long> TGResourceId { get; set; }
        public Nullable<long> ReportResourceId { get; set; }
        public string ClientID { get; set; }
        public string Authority { get; set; }
        public string AuthType { get; set; }
        public string ServerID { get; set; }
        public string Secret { get; set; }
        public string ServerScope { get; set; }
        public string EntityRef { get; set; }
        public string BranchIdentifiers { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetUsers> AspNetUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Branches> Branches { get; set; }
        public virtual Resources Resources { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Logs> Logs { get; set; }
    }
}
