//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Migrator29EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOG
    {
        public int LOG_CODIGO { get; set; }
        public System.DateTime LOG_FECHORA { get; set; }
        public int USU_CODIGO { get; set; }
        public string TER_CODIGO { get; set; }
        public Nullable<long> TAR_ID { get; set; }
        public string TRA_CODIGO { get; set; }
        public string LOG_DESCRIPCION { get; set; }
        public string TAR_EST_ANTERIOR { get; set; }
        public Nullable<int> AGE_CODIGO { get; set; }
    
        public virtual AGENCIA AGENCIA { get; set; }
        public virtual TARJETA TARJETA { get; set; }
        public virtual TRANSACCION TRANSACCION { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
