//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Migrator29EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOGAUDIT
    {
        public int LOGCODIGO { get; set; }
        public Nullable<int> USUCODIGO { get; set; }
        public string TRACODIGO { get; set; }
        public System.DateTime LOGFECHA { get; set; }
        public string LOGTERMINAL { get; set; }
        public string LOGDESCRIPCION { get; set; }
    
        public virtual TRANSACCION TRANSACCION { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
