//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Migrator29EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class MENU_PERFIL
    {
        public int PER_CODIGO { get; set; }
        public int MEN_CODIGO { get; set; }
        public string MP_ESTADO { get; set; }
    
        public virtual MENU MENU { get; set; }
        public virtual PERFIL PERFIL { get; set; }
    }
}
