//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Migrator29EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class MODELO_TARJETA
    {
        public string MTJ_CODIGO { get; set; }
        public string MTJ_DESCRIPCION { get; set; }
        public string MTJ_IMAGEN { get; set; }
        public Nullable<System.DateTime> MTJ_FECHA_CREACION { get; set; }
        public string MTJ_ESTADO { get; set; }
        public string MTJ_TIPO { get; set; }
    }
}
