//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Migrator29EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Orders()
        {
            this.Cards = new HashSet<Cards>();
            this.OrdersTags = new HashSet<OrdersTags>();
        }
    
        public int Id { get; set; }
        public Nullable<int> ProfileId { get; set; }
        public Nullable<int> PrefixId { get; set; }
        public Nullable<int> State { get; set; }
        public Nullable<int> InitialSequential { get; set; }
        public Nullable<int> Quantity { get; set; }
        public System.DateTime CreationDate { get; set; }
        public Nullable<System.DateTime> NotifyDate { get; set; }
        public Nullable<System.DateTime> ClosingDate { get; set; }
        public string UserName { get; set; }
        public Nullable<bool> AutoGeneration { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cards> Cards { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdersTags> OrdersTags { get; set; }
    }
}
