//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Migrator29EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDEN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ORDEN()
        {
            this.TARJETA = new HashSet<TARJETA>();
        }
    
        public int ORD_CODIGO { get; set; }
        public System.DateTime ORD_FECHA_CREACION { get; set; }
        public Nullable<System.DateTime> ORD_FECHA_CIERRE { get; set; }
        public int ORD_TOTAL { get; set; }
        public string ORD_ESTADO { get; set; }
        public string ORD_TIPO { get; set; }
        public string INST_CODIGO { get; set; }
    
        public virtual INSTITUCION INSTITUCION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TARJETA> TARJETA { get; set; }
    }
}
