//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Migrator29EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prefixes
    {
        public int Id { get; set; }
        public Nullable<int> BINId { get; set; }
        public string Prefix { get; set; }
        public Nullable<int> Sequential { get; set; }
        public string FPEInfo { get; set; }
    
        public virtual BINs BINs { get; set; }
    }
}
