//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Migrator29EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class SOLICITUD_TARJETA
    {
        public string CLI_IDENTIFICACION { get; set; }
        public string CTA_NUMERO { get; set; }
        public string EST_SOLICITUD { get; set; }
        public string DES_SOLICITUD { get; set; }
    }
}
