//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Migrator29EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TARJETA_PROFILE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TARJETA_PROFILE()
        {
            this.TARJETA = new HashSet<TARJETA>();
        }
    
        public int ID { get; set; }
        public string IMK_AC_SPEC { get; set; }
        public string CVK_SPEC { get; set; }
        public Nullable<bool> VALIDAR_FECHA_T2 { get; set; }
        public string NOMBRE { get; set; }
        public string ICVK_SPEC { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TARJETA> TARJETA { get; set; }
    }
}
