//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Migrator29EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TARJETA_CUENTA
    {
        public int CLI_CODIGO { get; set; }
        public string INST_CODIGO { get; set; }
        public string CTA_NUMERO { get; set; }
        public string TAR_CTA_TIPO { get; set; }
        public string TAR_CTA_ESTADO { get; set; }
        public string TAR_CTA_OBSERVACIONES { get; set; }
        public int TIP_CTA_CODIGO { get; set; }
        public long TAR_ID { get; set; }
    
        public virtual INSTITUCION INSTITUCION { get; set; }
        public virtual TARJETA TARJETA { get; set; }
        public virtual TARJETA_CUENTA TARJETA_CUENTA1 { get; set; }
        public virtual TARJETA_CUENTA TARJETA_CUENTA2 { get; set; }
        public virtual TIPO_CUENTA TIPO_CUENTA { get; set; }
    }
}
