//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Migrator29EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TARJETA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TARJETA()
        {
            this.LOG = new HashSet<LOG>();
            this.LOG_ACTUALIZACIONES = new HashSet<LOG_ACTUALIZACIONES>();
            this.TARJETA_CUENTA = new HashSet<TARJETA_CUENTA>();
        }
    
        public string TAR_NUMERO { get; set; }
        public int TIP_TAR_CODIGO { get; set; }
        public int EST_TAR_CODIGO { get; set; }
        public System.DateTime TAR_FECHA_SOLICITUD { get; set; }
        public string TAR_OFFSET { get; set; }
        public Nullable<int> TAR_CUPO_DIARIO_ATM { get; set; }
        public Nullable<int> TAR_CUPO_DISP_ATM { get; set; }
        public Nullable<int> TAR_CUPO_DISP_POS { get; set; }
        public Nullable<int> TAR_CUPO_DIARIO_POS { get; set; }
        public System.DateTime TAR_FECHA_EXPIRACION { get; set; }
        public System.DateTime TAR_FECHA_ULTIMO_MOV { get; set; }
        public Nullable<System.DateTime> TAR_FECHA_ENTREGA { get; set; }
        public Nullable<System.DateTime> TAR_FECHA_ACTIVACION { get; set; }
        public Nullable<int> TAR_PIN_RETRIES { get; set; }
        public string TAR_NOMBRE_IMPRESO { get; set; }
        public int ORD_CODIGO { get; set; }
        public int AGE_CODIGO { get; set; }
        public string AGE_DESCRIPTION_E { get; set; }
        public string MTJ_TIPO { get; set; }
        public string MTJ_CODIGO { get; set; }
        public string TAR_TIPO_PAGO { get; set; }
        public string TAR_TIPO_OP { get; set; }
        public string TAR_OP_SMS { get; set; }
        public Nullable<int> TAR_TRANS_FREC { get; set; }
        public Nullable<int> TAR_TRANS_CONTA { get; set; }
        public string TAR_OFFSET_FIRST { get; set; }
        public string TAR_CELULAR { get; set; }
        public string TAR_ValPIN_HSM_Flag { get; set; }
        public Nullable<System.DateTime> TAR_FECHA_ULT_CAMBIOPIN { get; set; }
        public Nullable<int> TAR_DIAS_VAL_PIN { get; set; }
        public string TAR_CVV { get; set; }
        public Nullable<int> TAR_EMV_SEC { get; set; }
        public long TAR_ID { get; set; }
        public string TAR_HASH { get; set; }
        public Nullable<int> TAR_PROFILE { get; set; }
        public Nullable<System.DateTime> TAR_FECHA_ULTIMO_RETIRO { get; set; }
        public string TAR_NUMERO_E { get; set; }
    
        public virtual AGENCIA AGENCIA { get; set; }
        public virtual ESTADO_TARJETA ESTADO_TARJETA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LOG> LOG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LOG_ACTUALIZACIONES> LOG_ACTUALIZACIONES { get; set; }
        public virtual ORDEN ORDEN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TARJETA_CUENTA> TARJETA_CUENTA { get; set; }
        public virtual TARJETA TARJETA1 { get; set; }
        public virtual TARJETA TARJETA2 { get; set; }
        public virtual TARJETA_PROFILE TARJETA_PROFILE { get; set; }
        public virtual TIPO_TARJETA TIPO_TARJETA { get; set; }
    }
}
