//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Migrator29EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USUARIO()
        {
            this.LOG = new HashSet<LOG>();
            this.LOGAUDIT = new HashSet<LOGAUDIT>();
            this.USUARIO_PPAGO = new HashSet<USUARIO_PPAGO>();
        }
    
        public int USU_CODIGO { get; set; }
        public string USU_ALIAS { get; set; }
        public string USU_NOMBRE { get; set; }
        public string USU_CEDULA { get; set; }
        public string USU_CLAVE { get; set; }
        public string USU_ESTADO { get; set; }
        public System.DateTime USU_FECAPER { get; set; }
        public Nullable<System.DateTime> USU_FEC_CAMB_CLAVE { get; set; }
        public int PER_CODIGO { get; set; }
        public string INST_CODIGO { get; set; }
        public Nullable<int> AGE_CODIGO { get; set; }
        public string USU_CLAVE_ACTUALIZACION { get; set; }
        public string USU_PERMISO { get; set; }
        public string USU_FLAG_PIN { get; set; }
        public string SALT { get; set; }
        public string SHA_PWD { get; set; }
    
        public virtual AGENCIA AGENCIA { get; set; }
        public virtual INSTITUCION INSTITUCION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LOG> LOG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LOGAUDIT> LOGAUDIT { get; set; }
        public virtual PERFIL PERFIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USUARIO_PPAGO> USUARIO_PPAGO { get; set; }
    }
}
