//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Migrator29EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO_PPAGO
    {
        public int USUCODIGO { get; set; }
        public string ENTCODIGO { get; set; }
        public int SUCCODIGO { get; set; }
        public int PPACODIGO { get; set; }
    
        public virtual AGENCIA AGENCIA { get; set; }
        public virtual INSTITUCION INSTITUCION { get; set; }
        public virtual PUNTOPAGO PUNTOPAGO { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
